# -*- coding: utf-8 -*-
"""graduation factors Linear Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZ98hbiAL_-T9obxTPPOs0JE-AAUIcTr
"""

import numpy as np
import pandas as pd
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Filtering out the warnings
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Admission_Predict.csv')
df

df.info()

df.isnull().sum()

df.shape

df.describe()

plt.figure(figsize=(20,10))
plt.subplot(2,3,1)
sns.boxplot(df['GRE Score'])
plt.subplot(2,3,2)
sns.boxplot(df['TOEFL Score'])
plt.subplot(2,3,3)
sns.boxplot(df['CGPA'])
plt.subplot(2,3,4)
sns.boxplot(df['University Rating'])
plt.show()

# most of the students gre score is around 317
# highest is 340 and lowest being 308
# most scores between 308 and 325
# we can interprate the same for the other factors

plt.scatter(df['GRE Score'],df['CGPA'])

plt.figure(figsize=(20,10))
sns.heatmap(df.corr(),annot=True)

sns.pairplot(df)

df.drop(columns=['Serial No.'], inplace=True)

from sklearn.model_selection import train_test_split

df_train,df_test=train_test_split(df,train_size= 0.70, test_size=0.30, random_state=100)

df_train.shape

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df_train= pd.DataFrame(scaler.fit_transform(df_train),columns=df_train.columns,index=df_train.index)

df_train.describe()

plt.figure(figsize=(20,10))
sns.heatmap(df_train.corr(),annot=True)

import statsmodels.api as sm

y_train = df_train.pop('Chance of Admit ')
x_train = sm.add_constant(df_train)

from statsmodels.stats.outliers_influence import variance_inflation_factor
X_train_const = sm.add_constant(x_train)
vif = pd.DataFrame()
vif['Feature'] = X_train_const.columns
vif['VIF'] = [
    variance_inflation_factor(X_train_const.values, i)
    for i in range(X_train_const.shape[1])
]

vif.sort_values(by='VIF', ascending=False)

lr = sm.OLS(y_train, X_train_const).fit()
lr.summary()

x_train.drop(columns=['University Rating'],inplace=True)

X_train_const = sm.add_constant(x_train)
model = sm.OLS(y_train, X_train_const).fit()
model.summary()

x_train.drop(columns=['SOP'],inplace=True)

X_train_const = sm.add_constant(x_train)
model = sm.OLS(y_train, X_train_const).fit()
model.summary()

y_train_pred = model.predict(X_train_const)

sns.histplot(y_train - y_train_pred, bins=20, kde=True)
plt.show()

plt.scatter(y_train, y_train_pred)

plt.scatter(y_train_pred, y_train - y_train_pred)
plt.axhline(y=0, color='r', linestyle='--')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.show()

df_test= pd.DataFrame(scaler.fit_transform(df_test),columns=df_test.columns,index=df_test.index)

df_test

df_test.drop(columns=['University Rating'],inplace=True)

df_test.drop(columns=['SOP'],inplace=True)

df_test.describe()

y_test = df_test.pop('Chance of Admit ')

x_test = df_test

x_test_sm = sm.add_constant ( x_test)

x_test_sm

y_test_pred = model.predict(x_test_sm)

plt.scatter(y_test, y_test_pred)