# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x__yZ8pQoOnFMODDYLHno3nUti0HNerD
"""

import numpy as np
import pandas as pd
# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Filtering out the warnings
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Admission_Predict.csv')
df

df['Admit'] = df['Chance of Admit '] > 0.7
df['Admit'] = df['Admit'].astype(int)
df['Admit']

df.columns

df.drop('Serial No.',axis=1,inplace=True)

df.drop('University Rating',axis=1,inplace=True)

df.drop('Chance of Admit ',axis=1,inplace=True)

Conversion_rate = (sum(df['Admit'])/len(df['Admit'].index))*100
Conversion_rate

y = df['Admit']
x = df.drop('Admit',axis=1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
from sklearn import preprocessing

logm1 = sm.GLM(y_train,(sm.add_constant(X_train)),family = sm.families.Binomial())
logm1.fit().summary()

from statsmodels.stats.outliers_influence import variance_inflation_factor
X_train_const = sm.add_constant(X_train)
vif = pd.DataFrame()
vif['Feature'] = X_train_const.columns
vif['VIF'] = [
    variance_inflation_factor(X_train_const.values, i)
    for i in range(X_train_const.shape[1])
]

vif.sort_values(by='VIF', ascending=False)

X_train.drop('SOP',inplace=True,axis=1)

logm1 = sm.GLM(y_train,(sm.add_constant(X_train)),family = sm.families.Binomial())
logm1.fit().summary()

X_train.drop('TOEFL Score',inplace=True,axis=1)

logm1 = sm.GLM(y_train,(sm.add_constant(X_train)),family = sm.families.Binomial())

result = logm1.fit()
result.summary()

y_train_prob = result.predict(sm.add_constant(X_train))
y_train_prob.head()

y_train.head()

train_results = pd.concat([y_train, y_train_prob], axis=1)

train_results.columns = ['Admit', 'Probability']

train_results

train_results['Predicted_Admit'] = train_results['Probability'].map(lambda x : 1 if x > 0.7  else 0)

train_results

from sklearn import metrics

confusion = metrics.confusion_matrix(train_results.Admit, train_results.Predicted_Admit )
print(confusion)

print(metrics.accuracy_score(train_results.Admit, train_results.Predicted_Admit ))

TP = confusion[1,1] # true positive
TN = confusion[0,0] # true negatives
FP = confusion[0,1] # false positives
FN = confusion[1,0] # false negatives

TP / float(TP+FN)

TN / float(TN+FP)

print(FP/ float(TN+FP))

print (TP / float(TP+FP))

print (TN / float(TN+ FN))

def draw_roc( actual, probs ):
    fpr, tpr, thresholds = metrics.roc_curve( actual, probs,
                                              drop_intermediate = False )
    auc_score = metrics.roc_auc_score( actual, probs )
    plt.figure(figsize=(5, 5))
    plt.plot( fpr, tpr, label='ROC curve (area = %0.2f)' % auc_score )
    plt.plot([0, 1], [0, 1], 'k--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate or [1 - True Negative Rate]')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic example')
    plt.legend(loc="lower right")
    plt.show()

    return None

fpr, tpr, thresholds = metrics.roc_curve(train_results.Admit, train_results.Predicted_Admit, drop_intermediate = False )

draw_roc(train_results.Admit, train_results.Predicted_Admit)

numbers = [float(x)/10 for x in range(10)]
for i in numbers:
    train_results[i]= train_results.Probability.map(lambda x: 1 if x > i else 0)
train_results.head()

# Now let's calculate accuracy sensitivity and specificity for various probability cutoffs.
cutoff_df = pd.DataFrame( columns = ['prob','accuracy','sensi','speci'])
from sklearn.metrics import confusion_matrix

# TP = confusion[1,1] # true positive
# TN = confusion[0,0] # true negatives
# FP = confusion[0,1] # false positives
# FN = confusion[1,0] # false negatives

num = [0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
for i in num:
    cm1 = metrics.confusion_matrix(train_results.Admit, train_results[i] )
    total1=sum(sum(cm1))
    accuracy = (cm1[0,0]+cm1[1,1])/total1

    speci = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    sensi = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    cutoff_df.loc[i] =[ i ,accuracy,sensi,speci]
print(cutoff_df)

cutoff_df.plot.line(x='prob', y=['accuracy','sensi','speci'])
plt.show()

train_results['final_predicted'] = train_results.Probability.map( lambda x: 1 if x > 0.5 else 0)

train_results.head()

print(metrics.accuracy_score(train_results.Admit, train_results.Predicted_Admit ))

confusion2 = metrics.confusion_matrix(train_results.Admit, train_results.final_predicted )
confusion2

TP = confusion2[1,1] # true positive
TN = confusion2[0,0] # true negatives
FP = confusion2[0,1] # false positives
FN = confusion2[1,0] # false negatives

TP / float(TP+FN)

print(FP/ float(TN+FP))

print (TP / float(TP+FP))

print (TN / float(TN+ FN))

from sklearn.metrics import precision_recall_curve

train_results.Admit, train_results.Predicted_Admit

p, r, thresholds = precision_recall_curve(train_results.Admit, train_results.Probability)

plt.plot(thresholds, p[:-1], "g-")
plt.plot(thresholds, r[:-1], "r-")
plt.show()

Recall = TP / float(TP+FN)
Recall

Precision = TP / float(TP+FP)
Precision

F1_score = (2* Recall * Precision)/ (Recall+Precision)
F1_score



